### ISSUE TITLE
User can search by author or title

### ISSUE THREAD

**Issue by allygreven** [allygreven/front-end-project#1]
## ⚙️ Feature

Users will want to search for their favorite book or author

## 📐 Functionality

Display and use the navigation bar to toggle through different pages, and search by title or by author for a book

## 🖼️ Wireframes

![user can view their entries mobile] 
<img width="290" alt="Screenshot 2024-11-26 at 3 42 45 PM" src="https://github.com/user-attachments/assets/db9884e8-f1f8-43f4-93a2-09c0bd1423f2">

![user can view their entries desktop] 
<img width="361" alt="Screenshot 2024-11-27 at 11 55 52 AM" src="https://github.com/user-attachments/assets/1251d5ce-88de-4391-9ee9-8ddc8f34d506">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div [data-view= 'navBar']` to the html
- [x] Add an unordered list containing all navBar elements in html
- [x] Add navigation items to the navigation bar unordered list for all clickable items by adding anchor attributes
- [x] Create a search bar under the navigation bar
- [x] Search bar results should be pulled from [filtered] Google Books API
- [x] User can see all book covers/titles/authors of search results
- [x] Add background photos and text layout on html & CSS 
- [x] Format in CSS for appropriate media dimensions
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
