### ISSUE TITLE
User can see 'genres' page

### ISSUE THREAD

**Issue by allygreven** [allygreven/front-end-project#2]
## ⚙️ Feature

User can view books by genres

## 📐 Functionality

Display the different genres to click on and viewSwap to different genre pages

## 🖼️ Wireframes

<img width="734" alt="Screenshot 2024-12-04 at 5 56 27 PM" src="https://github.com/user-attachments/assets/0086564a-0071-47b7-837e-56e0833ed723">
<img width="135" alt="Screenshot 2024-12-04 at 5 56 41 PM" src="https://github.com/user-attachments/assets/789ee3cd-d043-47f5-be06-38d7484da9dd">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create 'data-view' for genres page
- [ ] Create HTML photos for genres
- [ ] Update viewSwap function that will hide genres when on homepage but show when clicked on eventListener function
- [ ] Create eventListener function when 'Genres' is clicked to take you to genres page
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
