### ISSUE TITLE
User can add books to ‘favorites’

### ISSUE THREAD

**Issue by allygreven** [allygreven/front-end-project#3]
## ⚙️ Feature

User can add books to their favorites

## 📐 Functionality

User can click on a heart on the corner of any book cover and add it to their favorites where all of their favorited books will be displayed

## 🖼️ Wireframes

<img width="399" alt="Screenshot 2024-12-05 at 10 10 24 AM" src="https://github.com/user-attachments/assets/9a290023-e333-47f2-8de7-6362a3e9f964">
<img width="130" alt="Screenshot 2024-12-05 at 10 10 14 AM" src="https://github.com/user-attachments/assets/c79fd7cc-25c9-4074-83bf-a3d38b5db06a">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update renderImages() to add a heart to the book covers that is hidden until hovered over
- [x] Add a 'click' eventListener for when heart is clicked, which pushes the book covers to the 'favorites' page
- [x] Update viewSwap() to show 'favorites' page view when 'favorites' link is clicked
- [x] Update the title on the page to 'Favorites' on top of 'bookshelf-photo' in 'favorites' view
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
